package com.main.playervscomputer;

import java.util.Scanner;

public class App {

	public static void main(String[] args) {

		Scanner scan = new Scanner(System.in);
		String value = "";

		Player player1 = new Player();
		Computer computer = new Computer();

		player1.setId(1);
		player1.setName("Player 1");

		System.out.println("** R stands for Rock, P stands for Paper, S stands for Scissors **\n");

		System.out.println("Hi " + player1.getName() + " , Please enter any one of the values - R, P, S");

		value = scan.next();

		while (!"R".equalsIgnoreCase(value) && !"P".equalsIgnoreCase(value) && !"S".equalsIgnoreCase(value)) {
			System.out.println("You have entered Invalid value, Enter any one of R, P, S ");
			value = scan.next();
		}

		player1.setValue(value);
		computer.setValue();
		computer.setId(2);
		computer.setName("Computer");

		System.out.println("The value chosen/generated by Computer is - " + computer.getValue() + "\n");

		if (player1.getValue().equalsIgnoreCase(computer.getValue())) {
			System.out.println("Game is Draw");
		} else {
			Player winner = new Game().play(player1, computer);

			System.out.println("The Winner is - " + winner.getName());
		}

		scan.close();
	}

}
